import React from 'react';
import { 
  BookOpen, X, Coins, TrendingUp, 
  BarChart2, Rocket, Award, Zap, 
  RefreshCw, Globe, MessageSquare, 
  Settings, ArrowRight, AlertTriangle
} from 'lucide-react';

interface TokenTycoonGuideProps {
  isOpen: boolean;
  onClose: () => void;
}

export const TokenTycoonGuide: React.FC<TokenTycoonGuideProps> = ({ isOpen, onClose }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      <div className="absolute inset-0 bg-black/40 backdrop-blur-sm" onClick={onClose} />
      <div className="relative glass border border-white/10 rounded-xl p-6 w-[800px] max-h-[90vh] overflow-y-auto">
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-3">
            <BookOpen className="w-6 h-6 text-blue-400" />
            <h2 className="text-2xl font-semibold">Token Tycoon Guide</h2>
          </div>
          <button
            onClick={onClose}
            className="p-2 hover:bg-white/10 rounded-lg transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="space-y-8">
          {/* Introduction */}
          <section>
            <h3 className="text-xl font-medium mb-3">Introduction</h3>
            <p className="text-white/80 mb-4">
              Welcome to Token Tycoon! In this game, you'll build your own DeFi empire from scratch, starting with a simple yield farm and growing into a multi-chain ecosystem with tokens, DEXes, and more.
            </p>
            <div className="p-4 rounded-lg bg-blue-500/10 border border-blue-500/20">
              <div className="flex items-center gap-2 mb-2">
                <Coins className="w-5 h-5 text-blue-400" />
                <span className="font-medium">Game Objective</span>
              </div>
              <p className="text-white/80">
                Your goal is to generate as much TVL (Total Value Locked) as possible, launch tokens and DEXes, and eventually prestige to gain permanent multipliers and unlock new features.
              </p>
            </div>
          </section>

          {/* Resources */}
          <section>
            <h3 className="text-xl font-medium mb-3">Resources</h3>
            <p className="text-white/80 mb-4">
              There are three main resources in Token Tycoon:
            </p>
            <div className="grid grid-cols-3 gap-4">
              <div className="p-4 rounded-lg bg-blue-500/10 border border-blue-500/20">
                <div className="flex items-center gap-2 mb-2">
                  <BarChart2 className="w-5 h-5 text-blue-400" />
                  <span className="font-medium">TVL</span>
                </div>
                <p className="text-white/80 text-sm">
                  Total Value Locked is the foundation of your empire. Generate it by clicking and through passive sources.
                </p>
              </div>
              <div className="p-4 rounded-lg bg-green-500/10 border border-green-500/20">
                <div className="flex items-center gap-2 mb-2">
                  <Coins className="w-5 h-5 text-green-400" />
                  <span className="font-medium">Tokens</span>
                </div>
                <p className="text-white/80 text-sm">
                  Tokens are generated by farms and by converting TVL. Use them to buy and upgrade farms.
                </p>
              </div>
              <div className="p-4 rounded-lg bg-yellow-500/10 border border-yellow-500/20">
                <div className="flex items-center gap-2 mb-2">
                  <Coins className="w-5 h-5 text-yellow-400" />
                  <span className="font-medium">DEXGOLD</span>
                </div>
                <p className="text-white/80 text-sm">
                  Premium currency obtained by converting tokens. Used for launching tokens, DEXes, and buying upgrades.
                </p>
              </div>
            </div>
          </section>

          {/* Core Mechanics */}
          <section>
            <h3 className="text-xl font-medium mb-3">Core Mechanics</h3>
            <div className="space-y-4">
              <div className="p-4 rounded-lg bg-white/5">
                <div className="flex items-center gap-2 mb-2">
                  <Zap className="w-5 h-5 text-purple-400" />
                  <span className="font-medium">Clicking</span>
                </div>
                <p className="text-white/80 text-sm mb-2">
                  Click the TVL button to generate TVL. Your click power determines how much TVL you generate per click.
                </p>
                <div className="text-sm text-white/60">
                  Tip: Upgrade your click power early to progress faster.
                </div>
              </div>

              <div className="p-4 rounded-lg bg-white/5">
                <div className="flex items-center gap-2 mb-2">
                  <RefreshCw className="w-5 h-5 text-green-400" />
                  <span className="font-medium">Conversions</span>
                </div>
                <p className="text-white/80 text-sm mb-2">
                  Convert resources up the chain: TVL → Tokens → DEXGOLD. Each conversion is a step up in value.
                </p>
                <div className="text-sm text-white/60">
                  Conversion rates:
                  <ul className="list-disc list-inside mt-1">
                    <li>100 TVL → 10 Tokens (10:1 ratio)</li>
                    <li>100 Tokens → 1 DEXGOLD (100:1 ratio)</li>
                  </ul>
                </div>
              </div>

              <div className="p-4 rounded-lg bg-white/5">
                <div className="flex items-center gap-2 mb-2">
                  <TrendingUp className="w-5 h-5 text-blue-400" />
                  <span className="font-medium">Farms</span>
                </div>
                <p className="text-white/80 text-sm mb-2">
                  Farms generate tokens passively. Buy new farms and upgrade existing ones to increase your token generation.
                </p>
                <div className="text-sm text-white/60">
                  Tip: Harvest farms regularly to collect tokens, or upgrade them to auto-harvest.
                </div>
              </div>
            </div>
          </section>

          {/* Advanced Features */}
          <section>
            <h3 className="text-xl font-medium mb-3">Advanced Features</h3>
            <div className="space-y-4">
              <div className="p-4 rounded-lg bg-white/5">
                <div className="flex items-center gap-2 mb-2">
                  <Rocket className="w-5 h-5 text-pink-400" />
                  <span className="font-medium">Launching Tokens</span>
                </div>
                <p className="text-white/80 text-sm mb-2">
                  Spend DEXGOLD to launch tokens. Each token provides passive TVL generation.
                </p>
                <div className="flex items-center gap-2 mt-2 text-sm text-red-400">
                  <AlertTriangle className="w-4 h-4" />
                  <span>Beware of rug pull risk! Some tokens may fail and lose your investment.</span>
                </div>
              </div>

              <div className="p-4 rounded-lg bg-white/5">
                <div className="flex items-center gap-2 mb-2">
                  <MessageSquare className="w-5 h-5 text-indigo-400" />
                  <span className="font-medium">Creating DEXes</span>
                </div>
                <p className="text-white/80 text-sm mb-2">
                  Launch DEXes to boost your TVL generation. DEXes provide a percentage boost based on your current TVL.
                </p>
                <div className="text-sm text-white/60">
                  Tip: DEXes become more valuable as your TVL grows, making them a good long-term investment.
                </div>
              </div>

              <div className="p-4 rounded-lg bg-white/5">
                <div className="flex items-center gap-2 mb-2">
                  <Globe className="w-5 h-5 text-blue-400" />
                  <span className="font-medium">Blockchain Networks</span>
                </div>
                <p className="text-white/80 text-sm mb-2">
                  Different blockchain networks offer different multipliers. Unlock new chains through upgrades or prestige.
                </p>
                <div className="grid grid-cols-2 gap-2 mt-2">
                  <div className="text-sm">
                    <span className="text-white/60">Ethereum:</span> 1.0x multiplier
                  </div>
                  <div className="text-sm">
                    <span className="text-white/60">Arbitrum:</span> 1.2x multiplier
                  </div>
                  <div className="text-sm">
                    <span className="text-white/60">Base:</span> 1.3x multiplier
                  </div>
                  <div className="text-sm">
                    <span className="text-white/60">Solana:</span> 1.5x multiplier
                  </div>
                </div>
              </div>

              <div className="p-4 rounded-lg bg-white/5">
                <div className="flex items-center gap-2 mb-2">
                  <Settings className="w-5 h-5 text-orange-400" />
                  <span className="font-medium">Upgrades</span>
                </div>
                <p className="text-white/80 text-sm mb-2">
                  Buy upgrades to improve various aspects of your empire. Some upgrades increase click power, others boost yields or unlock new chains.
                </p>
                <div className="text-sm text-white/60">
                  Tip: Prioritize Auto Clicker and Click Power early on to accelerate your progress.
                </div>
              </div>
            </div>
          </section>

          {/* Prestige System */}
          <section>
            <h3 className="text-xl font-medium mb-3">Prestige System</h3>
            <div className="p-4 rounded-lg bg-gradient-to-r from-purple-500/20 to-pink-500/20 border border-purple-500/20">
              <div className="flex items-center gap-2 mb-3">
                <Award className="w-5 h-5 text-purple-400" />
                <span className="font-medium">Prestige Mechanics</span>
              </div>
              <p className="text-white/80 text-sm mb-4">
                Once you reach $1,000,000 TVL, you can prestige to reset your progress but gain permanent multipliers and unlock new features.
              </p>
              
              <div className="space-y-2">
                <div className="flex items-center gap-2">
                  <ArrowRight className="w-4 h-4 text-purple-400" />
                  <span className="text-white/80 text-sm">Each prestige level increases your multiplier by 0.5x</span>
                </div>
                <div className="flex items-center gap-2">
                  <ArrowRight className="w-4 h-4 text-purple-400" />
                  <span className="text-white/80 text-sm">Unlocks new chains based on prestige level</span>
                </div>
                <div className="flex items-center gap-2">
                  <ArrowRight className="w-4 h-4 text-purple-400" />
                  <span className="text-white/80 text-sm">Unlocks prestige-specific upgrades</span>
                </div>
                <div className="flex items-center gap-2">
                  <ArrowRight className="w-4 h-4 text-purple-400" />
                  <span className="text-white/80 text-sm">Achievements remain unlocked after prestige</span>
                </div>
              </div>
            </div>
          </section>

          {/* Strategy Tips */}
          <section>
            <h3 className="text-xl font-medium mb-3">Strategy Tips</h3>
            <div className="grid grid-cols-2 gap-4">
              <div className="p-4 rounded-lg bg-white/5">
                <div className="font-medium mb-2">Early Game (0-10K TVL)</div>
                <ul className="space-y-1 text-sm text-white/80">
                  <li>• Focus on clicking and upgrading click power</li>
                  <li>• Buy Auto Clicker as soon as possible</li>
                  <li>• Upgrade your first farm to level 3-5</li>
                  <li>• Convert TVL to tokens regularly</li>
                </ul>
              </div>
              
              <div className="p-4 rounded-lg bg-white/5">
                <div className="font-medium mb-2">Mid Game (10K-100K TVL)</div>
                <ul className="space-y-1 text-sm text-white/80">
                  <li>• Buy additional farms</li>
                  <li>• Launch your first token</li>
                  <li>• Focus on yield-boosting upgrades</li>
                  <li>• Start converting tokens to DEXGOLD</li>
                </ul>
              </div>
              
              <div className="p-4 rounded-lg bg-white/5">
                <div className="font-medium mb-2">Late Game (100K-1M TVL)</div>
                <ul className="space-y-1 text-sm text-white/80">
                  <li>• Launch DEXes for scaling TVL generation</li>
                  <li>• Unlock and utilize different chains</li>
                  <li>• Launch multiple tokens for passive income</li>
                  <li>• Prepare for your first prestige</li>
                </ul>
              </div>
              
              <div className="p-4 rounded-lg bg-white/5">
                <div className="font-medium mb-2">Post-Prestige</div>
                <ul className="space-y-1 text-sm text-white/80">
                  <li>• Take advantage of your multiplier</li>
                  <li>• Unlock prestige-specific upgrades</li>
                  <li>• Expand to new chains immediately</li>
                  <li>• Progress will be much faster each prestige</li>
                </ul>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
};